### ISSUE TITLE
Traceback (most recent call last):   File "slowloris.py", line 6, in <module>     import ssl   File "/usr/local/lib/python3.7/ssl.py", line 98, in <module>     import _ssl             # if we can't import it, let the error propagate ModuleNotFoundError: No module named '_ssl'

### ISSUE THREAD

**Issue by IamFadedGamer** [gkbrk/slowloris#26]
What am I doing wrong?

**Comment by gkbrk** [comment]
* Do you have OpenSSL installed?
* Did you build Python yourself or are you using a distro package?
* Which distro?
* Which command did you use to run the tool?

**Comment by gkbrk** [comment]
Fixed with 5cb7d9a3a75.
