### ISSUE TITLE
AttributeError: 'SSLSocket' object has no attribute 'send_line'

### ISSUE THREAD

**Issue by ggghuilei** [gkbrk/slowloris#49]
[root@localhost slowloris]# python3 slowloris.py -p=443 --https 172.19.6.213
[21-01-2021 14:08:15] Importing ssl module
[21-01-2021 14:08:15] Attacking 172.19.6.213 with 150 sockets.
[21-01-2021 14:08:15] Creating sockets...
Traceback (most recent call last):
  File "slowloris.py", line 217, in <module>
    main()
  File "slowloris.py", line 181, in main
    s = init_socket(ip)
  File "slowloris.py", line 161, in init_socket
    s.send_line(f"GET /?{random.randint(0, 2000)} HTTP/1.1")
AttributeError: 'SSLSocket' object has no attribute 'send_line'

**Comment by gkbrk** [comment]
It looks like a recent refactor (456ad820008) broke this. Probably need to take send_line out of the sockets again.

**Comment by gkbrk** [comment]
Fixed with 6c6ec59ada.
