### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Boca-NeedM** [gkbrk/slowloris#70]
slowloris example.com
Traceback (most recent call last):
  File "/usr/local/bin/slowloris", line 7, in <module>
    from slowloris import main
  File "/usr/local/lib/python3.5/dist-packages/slowloris.py", line 108
    line = f"{line}\r\n"
                       ^
SyntaxError: invalid syntax

**Comment by RGM12** [comment]
python3 slowloris.py example.com
  File "slowloris.py", line 108
    line = f"{line}\r\n"
                       ^
SyntaxError: invalid syntax

**Comment by gkbrk** [comment]
Can you post the output of `python3 --version`?

**Comment by Boca-NeedM** [comment]
python3 --version
Python 3.5.3


1 okt. 2022 15:12 van ***@***.***:

**Comment by mamadk1994** [comment]
what's wrong????


27-10-2022 17:10:48] Attacking my.uk.ac.ir/ with 1000 sockets.
[27-10-2022 17:10:48] Creating sockets...
[27-10-2022 17:10:48] Creating socket nr 0
[27-10-2022 17:10:48] [Errno -2] Name or service not known
[27-10-2022 17:10:48] Sending keep-alive headers...
[27-10-2022 17:10:48] Socket count: 0
[27-10-2022 17:10:48] Creating 1000 new sockets...
[27-10-2022 17:10:48] Error in Slowloris iteration: 'Namespace' object has no attribute 'ip'

**Comment by gkbrk** [comment]
Python 3.5 was released in 2015 and hit end-of-life in 2020. I recommend migrating to something more recent.
