### ISSUE TITLE
TypeError: 'Bar' object is not an iterator

### ISSUE THREAD

**Issue by lekosbelas** [gkbrk/slowloris#91]
└─# python3 SlowLoris.py fxxxxx.com 80 100 10
Traceback (most recent call last):
File "/home/kali/Downloads/Slow-Loris/SlowLoris.py", line 66, in 
main()
File "/home/kali/Downloads/Slow-Loris/SlowLoris.py", line 41, in main
next(bar)
TypeError: 'Bar' object is not an iterator

**Comment by gkbrk** [comment]
What kind of janky script did you download? My code doesn't have anything like that.

**Comment by lekosbelas** [comment]
Chill bro, I mistaken the post obviously.
